vaadin/quarkus

- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/service/EventObserver.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/EventsTest.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/ServiceTest.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
Feature allows to listen mentioned events using @Observes methods.
fixes #21
> feat: fire session init/destroy and ui init events via bean manager

- integration-tests/pom.xml
Quarkus bom explicitly defines a dependency on guava but that version clasehs with the one required by the selenium version used by vaadin testbench.
> test: Pin guava version to avoid dependency clash

- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/AppShellConfig.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/push/PushUpdateDivView.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/PushSmokeTest.java
Adds integration test to ensure PUSH works.
At the moment only long polling is supported.
Part of #4
Closes #42
> chore: Add smoke test for PUSH (#42)

- runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusResourceProvider.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServlet.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
- runtime/src/main/java/com/vaadin/quarkus/context/AbstractContext.java
- runtime/src/main/java/com/vaadin/quarkus/context/AbstractContextualStorageManager.java
> chore: Adding missing javadocs

- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
If `VaadinServlet` without `@WebServlet` annotation present (like when `vaadin-cdi` happened to be in classpath) currently `quarkusBuild` will fail with NPE.
This patch skips such servlets with a warning in log.
Fixes #76
> Skip user `VaadinServlet`s without @WebServlet instead of NPE on `quarkusBuild`

- integration-tests/development/pom.xml
When running in development mode we need to add Vite --host flag
so Vite client websocket connection will work when tests are
executed on a remote browser
> test: set --host Vite flag in development mode

- pom.xml
Pins open telemetry dependencies version to avoid conflicts in runtime, like
```
java.lang.NoSuchMethodError: 'io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.addTracerProviderCustomizer(java.util.function.BiFunction)'
```
> chore: Use open telemetry BOM to avoid version conflicts

- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
When using Vite, DevModeInitializer blocks dev-server startup until a VaadinServlet is deployed because it needs to get the servlet path to use. If the container lazily loads servlets, Vite will not start until the first HTTP request for the Vaadin servlet is received.
This change sets load-on-startup feature for all Vaadin Servlet registered by the extension, to ensure that Vite is loaded at the startup of the Web application.
A warning message is shown for custom Vaadin servlets that do not set loadOnStartup on WebServlet annotation.
Part of vaadin/flow#14479
> fix: set load-on-startup for automatically registered Vaadin servlets

- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
- integration-tests/common-test-code/pom.xml
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/CustomAnnotatedEnpoint.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/CustomWebsocketsIT.java
- integration-tests/custom-websocket-dependency/pom.xml
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/DependencyAnnotatedWS.java
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/SimpleEndpoint.java
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/SimpleEndpointConfig.java
- integration-tests/development/pom.xml
- integration-tests/development/vite.generated.ts
- integration-tests/pom.xml
- integration-tests/production/pom.xml
- integration-tests/production/vite.generated.ts
- runtime/src/main/java/com/vaadin/quarkus/EnableWebsockets.java
The workaround added to make PUSH work in Quarkus prevents the usage of custom annotated websocket endpoint. This change allows them to work along Vaadin PUSH.
Fixes #78
> fix: make sure annotated endpoints works along Vaadin PUSH

- integration-tests/common-test-code/pom.xml
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/CustomAnnotatedEnpoint.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/CustomWebsocketsIT.java
- integration-tests/custom-websocket-dependency/pom.xml
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/DependencyAnnotatedWS.java
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/SimpleEndpoint.java
- integration-tests/custom-websocket-dependency/src/main/java/org/vaadin/sample/websockets/SimpleEndpointConfig.java
- integration-tests/development/pom.xml
- integration-tests/pom.xml
- integration-tests/production/pom.xml
- runtime/src/main/java/com/vaadin/quarkus/EnableWebsockets.java
The workaround added to make PUSH work in Quarkus prevents the usage of custom annotated websocket endpoint. This change allow them to work along Vaadin PUSH.
Fixes #78
> fix: make sure annotated endpoints works along Vaadin PUSH (CP: 1.1)

- integration-tests/development/pom.xml
- runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiatorFactory.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
- runtime/src/main/java/com/vaadin/quarkus/annotation/VaadinServiceEnabled.java
Replaced `Instantiator.init()` with `InstantiatorFactory`
> fix: updates after removal of deprecated Flow code

- pom.xml
- runtime/pom.xml
Updated project to use Quarkus 3 final version and replaced the removed quarkus-bootstrap-maven-plugin, as documented in the migration guide.
> chore: update to quarkus 3 final

- integration-tests/common-test-code/pom.xml
- integration-tests/development/pom.xml
- integration-tests/production/pom.xml
quarkus-undertow-websockets has been removed since Quarkus 2.8.
Replacement is quarkus-websockets.
> test: fixed quarkus websocket artifact

- pom.xml
Having the system property configured for failsafe plugin prevents selenium to automatically handle the chromedriver version, when the value is empty.
This change adds a profile, activated by the property presence, that propagates the value to failsafe only if explicitly set.
> test: propagate webdriver manager property only when provided

- pom.xml
Having the system property configured for failsafe plugin prevents selenium to automatically handle the chromedriver version, when the value is empty.
This change adds a profile, activated by the property presence, that propagates the value to failsafe only if explicitly set.
> test: propagate webdriver manager property only when provided (CP: 1.1)

- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SessionContextCloseIT.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SessionContextIT.java
Session context tests check the counter value hold by a session bean right after invalidating the Vaadin session. Since the counter is incremented in the PreDestroy hook, it may happen that when the test checks for the counter value, the callback has not yet been invoked. This change retries the counter check for at most on second, to preven ttest flakyness.
Fixes #126
> test: retry count assertion on session invalidation

- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/i18n/TranslationView.java
Resets the poll interval in the UI.access block so that the change is immediately pushed to the client and polling is stopped. Otherwise, the client will continue to poll until a UIDL request is sent the server.
> test: reset UI poll interval in UI.access block

- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/SmokeTestView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/DetailApartView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/DetailAssignedView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/EventView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/MainLayout.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/MasterView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/RootView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/sessioncontext/SessionContextView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uicontext/UIContextRootView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uicontext/UINormalScopedBeanView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uicontext/UIScopedLabel.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uicontext/UIScopedView.java
- integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uievents/UIEventsView.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SmokeTestIT.java
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/UIEventsIT.java
Also prevents console to being flooded by warning messages about Label used without a field.
> chore: replace deprecated Label with Span

- integration-tests/pom.xml
- pom.xml
Quarkus BOM declares JNA dependencies in a version older than the one
required by Vaadin License Checker.
Swapping Flow and Quarkus BOMs does not help because JNA is a transitive
dependency of license checker and Quarkus BOM wins becuase its
definition is nearest to the root of the dependency tree.
Pin JNA in the parent integration tests module fixes the issue.
> chore: pin JNA version to prevent wrong management

- pom.xml
Quarkus 3.8 is the latest LTS.
> chore: bump Quarkus to 3.8.4

- pom.xml
- runtime/src/main/resources/META-INF/quarkus-extension.yaml
Adds SCM info and link to Vaadin logo to the extension metadata to be shown on https://quarkus.io/extensions.
Fixes #162
> chore: improve extension metadata

- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
- integration-tests/development/pom.xml
- integration-tests/production/pom.xml
Development (e.g. vaadin-dev-server) and optional (e.g. flow-react) dependencies must not be present in the Vaadin platform indexed, to prevent NoClassDefFound errors at runtime, for example when running a production build with dev-server excluded.
This change adds a build step to index optional dependencies only if they are present in the project configuration.
Part of #158
> fix: index optional dependencies

- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
- integration-tests/development/pom.xml
- integration-tests/pom.xml
- integration-tests/production/pom.xml
- pom.xml
Development (e.g. vaadin-dev-server) and optional (e.g. flow-react) dependencies must not be present in the Vaadin platform indexed, to prevent NoClassDefFound errors at runtime, for example when running a production build with dev-server excluded.
This change adds a build step to index optional dependencies only if they are present in the project configuration.
Part of #158
> fix: index optional dependencies (#172) (CP: 2.0)

- integration-tests/development/pom.xml
- integration-tests/production/pom.xml
The flow-react artifact has been added in Flow 24.4. This change makes it possible to exclude it for
previous Flow versions by setting the vaadin.exclude-flow-react system property.
> test: allow to exclude flow-react for 24.3 tests (2.0)

- runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
- runtime/src/test/java/com/vaadin/quarkus/QuarkusInstantiatorDefaultsTest.java
- runtime/src/test/java/com/vaadin/quarkus/QuarkusInstantiatorTest.java
A MenuAccessControl instance is required when operating with MenuConfiguration. This change provides a default implementation if the user project does not define a specialized bean.
Fixes #175
> fix: provide default MenuAccessControl instance

- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/ServiceIT.java
Flow client introduced a little delay in session expiration handling to prevent issues with slow connections.
This change makes the test wait for notification to be shown before asserting on text message.
> test: wait for system messages notification

- .github/workflows/quarkus-snapshot.yaml
Also runs with Java 17 to prevent build failures because of issue update script using Java records.
> chore: bump Flow to 23.5 in quarkus ecosystem workflow

- runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
- runtime/src/test/java/com/vaadin/quarkus/QuarkusInstantiatorTest.java
Similar to Vaadin routes, also UI components may require dependency injection.
This change updates QuarkusInstantiator to try to use BeanManager to get a component instance, otherwise it fallbacks to the default instantiator.
To be noted, that UI components should have `@Dependant` or a proper Vaadin scope to work correctly with Vaadin; `@ApplicationScoped` and `@Singleton` must not be used.
Fixes #192
> fix: try using bean manager to instantiate components

- README.md
- build-tools/pom.xml
- deployment/pom.xml
- integration-tests/codestarts/pom.xml
- integration-tests/common-test-code/pom.xml
- integration-tests/custom-websocket-dependency/pom.xml
- integration-tests/development/pom.xml
- integration-tests/pom.xml
- integration-tests/production/pom.xml
- integration-tests/reusable-theme/pom.xml
- integration-tests/test-addons/addon-with-jandex/pom.xml
- integration-tests/test-addons/addon-without-jandex/pom.xml
- pom.xml
- runtime/pom.xml
Also updates Quarkus to 3.20 LTS, cleans up POM files and bumps several maven plugin and dependencies.
> chore: bump project to 2.2 and Vaadin to 24.8

- deployment/pom.xml
- deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/AbstractVaadinServiceExecutorTestSupport.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/QuarkusVaadinServletServiceAlternativeExecutorTest.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/QuarkusVaadinServletServiceAmbiguousExecutorTest.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/QuarkusVaadinServletServiceCustomExecutorTest.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/QuarkusVaadinServletServiceManagedExecutorTest.java
- deployment/src/test/java/com/vaadin/flow/quarkus/test/executor/TestQuarkusVaadinServletService.java
- runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
Enhances Quarkus VaadinService implementation trying to detect the best Executor option available at runtime. It first looks for an Executor bean annotated with `@VaadinServiceEnabled` and then it falls back to the Quarkus provided ManagedExecutor.
Closes #200
> feat: detect specific Executor for VaadinService

- build-tools/pom.xml
- deployment/pom.xml
- integration-tests/codestarts/pom.xml
- integration-tests/common-test-code/pom.xml
- integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SmokeTestIT.java
- integration-tests/custom-websocket-dependency/pom.xml
- integration-tests/development/pom.xml
- integration-tests/pom.xml
- integration-tests/production/pom.xml
- integration-tests/reusable-theme/pom.xml
- integration-tests/test-addons/addon-with-jandex/pom.xml
- integration-tests/test-addons/addon-without-jandex/pom.xml
- pom.xml
- runtime/pom.xml
- runtime/src/test/java/com/vaadin/quarkus/context/UIUnderTestContext.java
Also updates to Vaadin 25.0 and JakartaEE 11.
It uses Quarkus 3.24 (non LTS) waiting for the
3.27 LTS release in September/October.
> chore: bump project to 3.0
