runtime/pom.xml
runtime/src/main/java/com/vaadin/quarkus/QuarkusResourceProvider.java
runtime/src/test/java/com/vaadin/quarkus/ResourceProviderTest.java
runtime/src/test/resources/resource-provider/some-resource.json

Add a ResourceProvider for Quarkus.
fixes vaadin/flow#9713

feat: Add ResourceProvider

---

deployment/pom.xml
deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/TestServlet.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SmokeTest.java
runtime/pom.xml
runtime/src/main/java/com/vaadin/quarkus/BeanLookup.java
runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServlet.java
runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
runtime/src/main/java/com/vaadin/quarkus/annotation/VaadinServiceEnabled.java

Add support for CDI injection.

feat: CDI injection support for Routes

---

runtime/pom.xml
runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java
runtime/src/test/java/com/vaadin/quarkus/UsageStatisticsTest.java

Add usage statistics for devmode execution.
Closes #2

feat: Add usageStatistics call

---

pom.xml

chore: upgrade Quarkus version

---

deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/CustomException.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/ErrorHandlerView.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/ErrorParentView.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/routecontext/ErrorView.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/RouteContextTest.java

fix: recognize HasErrorParameter classes as beans

---

integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/service/TestErrorHandler.java
integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/service/TestSystemMessagesProvider.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/ServiceBeanTest.java
runtime/src/main/java/com/vaadin/quarkus/BeanLookup.java
runtime/src/main/java/com/vaadin/quarkus/QuarkusVaadinServletService.java

feat: set system messages and error handler using CDI beans

---

pom.xml

chore: add release profile, javadocs and source generation

---

build-tools/pom.xml
deployment/src/test/java/com/vaadin/flow/quarkus/test/VaadinQuarkusDevModeTest.java
deployment/src/test/java/com/vaadin/flow/quarkus/test/VaadinQuarkusTest.java
eclipse/VaadinCleanup.xml
eclipse/VaadinJavaConventions.xml
eclipse/flow.importorder
pom.xml
runtime/src/main/java/com/vaadin/quarkus/QuarkusInstantiator.java
runtime/src/main/java/com/vaadin/quarkus/QuarkusResourceProvider.java

chore: add formatter and format code base

---

pom.xml

chore: bump quarkus version to 2.3.0

---

pom.xml

update Quarkus to 2.6.0.Final and set flow as 10.0-SNAPSHOT

chore: Update quarkus and flow to latest

---

runtime/src/test/java/com/vaadin/quarkus/UsageStatisticsTest.java

Fix method name changed in vaadin/flow#12718

chore: Fix test to use new method name

---

deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java

@WebServlet.urlPatterns are read as string array from annotation.
@WebServlet.value is also taken into accout for mappings.
Added check to prevent NPE when reading init parameters.
Use @WebServlet.name as servlet name, if present.

fix: fixes on user servlet registrations

---

integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AbstractCdiIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/AddonsIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/PushSmokeIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/RemoveOldContentIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/RouteContextIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/ServiceIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SessionContextCloseIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SessionContextIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/SmokeTestIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/UIContextIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/quarkus/it/UIEventsIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/test/AbstractChromeIT.java
integration-tests/common-test-code/src/test/java/com/vaadin/flow/test/ScreenshotsOnFailureExtension.java
integration-tests/development/pom.xml
integration-tests/production/pom.xml
pom.xml

Configured maven failsafe plugin to run integration test and renamed
classes to match IT suffix.
Closes #40

chore: configure failsafe for integration test (#40)

---

integration-tests/test-addons/addon-with-jandex/src/main/java/org/vaadin/jandex/HelloWorldJandex.java
integration-tests/test-addons/addon-without-jandex/src/main/java/org/vaadin/nojandex/HelloWorld.java

Prevents compilation failures because of clashes
between lit and lit-html

test: upgrade axa-ch/input-text

---

pom.xml

chore: Update vaadin parent

---

pom.xml

chore: quarkus bump to 3.0.0.Alpha1

chore: quarkus bump to 3.0.0.Alpha1

---

runtime/src/test/java/com/vaadin/quarkus/TestQuarkusVaadinServletService.java

test: fix missing lookup mock

---

integration-tests/common-test-code/src/test/java/com/vaadin/flow/test/AbstractChromeIT.java

Fixing compilation error to not block the release.
AbstractChromeIt compilation error.

Fixed compilation error for  for not blocking release (AbstractChromeIt)

---

integration-tests/common-test-code/src/test/java/com/vaadin/flow/test/AbstractChromeIT.java

Fixing compilation error to not block the release.
AbstractChromeIt compilation error.

test: Fixed compilation error in AbstractChromeIT

---

integration-tests/common-test-code/src/test/java/com/vaadin/flow/test/AbstractChromeIT.java

Fixing compilation error to not block the release.
AbstractChromeIt compilation error.

Fixed compilation error in AbstractChromeIT.

---

integration-tests/common-test-code/src/main/java/com/vaadin/flow/quarkus/it/uievents/UIEventsView.java
runtime/src/main/java/com/vaadin/quarkus/context/RouteScopedContext.java

Some cleanup to the previous commit happened to the master.

chore: java doc adding behind Observer changes, and removing unrelated changes (private access modifier in UIEventsView).

---

.github/quarkus-ecosystem-test
.github/workflows/quarkus-snapshot.yaml

chore: added workflow for quarkus ecosystem CI integration

---

.github/workflows/quarkus-snapshot.yaml

The new job targets branch 1.1 for Quarkus 2.x

chore: added ecosystem job for Quarkus 2

---

.github/quarkus-ecosystem-test
integration-tests/common-test-code/pom.xml
integration-tests/development/pom.xml
integration-tests/production/pom.xml
pom.xml

Adds missing script for Quarkus ecosystem CI build

chore: added script for quarkus ecosystem build

---

integration-tests/codestarts/pom.xml
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/CodestartTestUtils.java
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionBuildCodestartTest.java
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionCodestartTest.java
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionPreReleaseCodestartTest.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionCodestartTest/testApplicationContents/dir-tree.snapshot
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_AppConfig.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_GreetService.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_MainView.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionPreReleaseCodestartTest/testApplicationContents/dir-tree.snapshot
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionPreReleaseCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_AppConfig.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionPreReleaseCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_GreetService.java
integration-tests/codestarts/src/test/resources/__snapshots__/VaadinExtensionPreReleaseCodestartTest/testApplicationContents/src_main_java_ilove_quark_us_example_MainView.java
integration-tests/pom.xml
runtime/pom.xml
runtime/src/main/codestarts/quarkus/flow-codestart/base/.gitignore
runtime/src/main/codestarts/quarkus/flow-codestart/base/README.tpl.qute.md
runtime/src/main/codestarts/quarkus/flow-codestart/base/frontend/themes/starter-theme/components/vaadin-text-field.css
runtime/src/main/codestarts/quarkus/flow-codestart/base/frontend/themes/starter-theme/styles.css
runtime/src/main/codestarts/quarkus/flow-codestart/base/frontend/themes/starter-theme/theme.json
runtime/src/main/codestarts/quarkus/flow-codestart/base/pom.xml.tpl.qute
runtime/src/main/codestarts/quarkus/flow-codestart/codestart.yml
runtime/src/main/codestarts/quarkus/flow-codestart/java/src/main/java/org/acme/example/AppConfig.java
runtime/src/main/codestarts/quarkus/flow-codestart/java/src/main/java/org/acme/example/GreetService.java
runtime/src/main/codestarts/quarkus/flow-codestart/java/src/main/java/org/acme/example/MainView.java
runtime/src/main/resources/META-INF/quarkus-extension.yaml

Added a codestart that provides a Flow application with an example view
Closes #112

feat: added codestart (#119) (CP: 1.1)

---

integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionBuildCodestartTest.java
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionCodestartTest.java
integration-tests/codestarts/src/test/java/com/vaadin/flow/quarkus/it/VaadinExtensionPreReleaseCodestartTest.java
pom.xml
runtime/pom.xml

Bump Quarkus to the least supported version on code.quarkus.io

chore: bump quarkus to 2.13

---

README.md

Improving README.md with the devUI URL param and how to reach it.
#125

chore: added explanation and URL how to reach devUI in development mode/profile

---

README.md

Improving README.md with the devUI URL param and how to reach it.
#125

chore: added explanation and URL how to reach devUI in development mode/profile  (CP.1.1)

---

runtime/src/main/codestarts/quarkus/flow-codestart/base/frontend/themes/starter-theme/components/vaadin-text-field.css
runtime/src/main/codestarts/quarkus/flow-codestart/base/frontend/themes/starter-theme/styles.css
runtime/src/main/codestarts/quarkus/flow-codestart/codestart.yml
runtime/src/main/resources/META-INF/quarkus-extension.yaml

chore: update documentation links

---

deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusNativeProcessor.java
deployment/src/main/java/com/vaadin/quarkus/deployment/nativebuild/AtmospherePatches.java
deployment/src/main/java/com/vaadin/quarkus/deployment/nativebuild/InjectableObjectFactoryFieldUsageRemovalMethodVisitor.java
runtime/src/main/java/com/vaadin/quarkus/graal/AtmosphereDeferredInitializer.java
runtime/src/main/java/com/vaadin/quarkus/graal/AtmosphereDeferredInitializerRecorder.java
runtime/src/main/java/com/vaadin/quarkus/graal/AtmosphereServletConfig.java
runtime/src/main/java/com/vaadin/quarkus/graal/DelayedInitBroadcaster.java
runtime/src/main/java/com/vaadin/quarkus/graal/DelayedSchedulerExecutorsFactory.java

Adds support for native image build by registering classes for reflection and patching Atmosphere.
Fixes #157

feat: add support for native image build

---

deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusNativeProcessor.java

Some Vaadin Java components like Grid and Combobox define methods using VaadinSpringDataHelper utility from vaadin-spring module. In a Quarkus application, that module is usually not present, and causes native build to fail.
This change provides a stub implementation that throws an exception when methods are invoked.
Fixes #194

fix: add replacement for VaadinSpringDataHelpers in native build

---

deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusNativeProcessor.java

fix: add native hint for feature flags file

---

pom.xml
runtime/src/test/java/com/vaadin/quarkus/TestQuarkusVaadinServletService.java

Also bumps the Flow version to 23.6

test: fix VaadinService test mock (1.1)
